### ISSUE TITLE
Support for authenticating against remote service

### ISSUE THREAD

**Issue by sazzer** [sazzer/graphql-tester#2]
Often a GraphQL Service will require authentication to perform all of the required actions. It would be useful to be able to do this in the test tool.

Ideally this should be flexible enough to support arbitrary authentication systems, and certainly it needs to be able to support authentications systems that are more complex than just Basic Auth - e.g. OAuth. In the most complicated case, the authentication details might be dependant on the payload that is being sent to the server.

**Comment by Naoto-Ida** [comment]
@sazzer I need this too, so I'm writing it right now.

**Comment by Naoto-Ida** [comment]
@sazzer I've just done a pull request #6 to fix this. Please check it out.

**Comment by sazzer** [comment]
Just merged it in and published as v0.0.5.

**Comment by Naoto-Ida** [comment]
Thanks!

**Comment by Naoto-Ida** [comment]
@sazzer Hey, I'm not that familiar with Travis-CLI, but it says `build: error` on the README.md now... could it be my changes?

**Comment by sazzer** [comment]
No, it's my fault. I updated the dependencies to the latest version in the
same release, and apparently it now no longer works on node v4. v5 still
builds fine though.

**Comment by Naoto-Ida** [comment]
@sazzer Ok, thanks.
